#!/usr/bin/env python3
"""
MiniLang Compiler — CLI Entry Point
=====================================
Command-line interface for compiling and running MiniLang programs.

Usage:
    python main.py run examples/fibonacci.mini          # Compile & run
    python main.py tokens examples/fibonacci.mini       # Show lexer output
    python main.py ast examples/fibonacci.mini           # Show AST
    python main.py ir examples/fibonacci.mini            # Show Three-Address Code
    python main.py optimize examples/fibonacci.mini      # Show optimized TAC
    python main.py bytecode examples/fibonacci.mini      # Show bytecode
    python main.py trace examples/fibonacci.mini         # Run with VM trace
    python main.py all examples/fibonacci.mini           # Show ALL stages
"""

import sys
import os

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from src.compiler import Compiler
from src.errors import CompilerError


def print_header(title):
    """Print a formatted section header."""
    print(f"\n{'═' * 60}")
    print(f"  {title}")
    print(f"{'═' * 60}")


def print_tokens(stages):
    """Display lexer output."""
    print_header("STAGE 1: LEXICAL ANALYSIS (Tokens)")
    print(f"  {'Type':<20} {'Value':<15} {'Line':>5} {'Col':>5}")
    print(f"  {'─' * 50}")
    for token in stages['tokens']:
        ttype = token.type.name
        value = repr(token.value) if isinstance(token.value, str) else str(token.value)
        print(f"  {ttype:<20} {value:<15} {token.line:>5} {token.column:>5}")
    print(f"\n  Total tokens: {len(stages['tokens'])}")


def print_ast(stages):
    """Display the AST."""
    print_header("STAGE 2: PARSING (Abstract Syntax Tree)")
    print(stages['ast'].pretty_print())


def print_symbol_table(stages):
    """Display the symbol table."""
    print_header("STAGE 3: SEMANTIC ANALYSIS (Symbol Table)")
    print(stages['symbol_table'].pretty_print())


def print_tac(stages):
    """Display Three-Address Code."""
    print_header("STAGE 4: INTERMEDIATE CODE (Three-Address Code)")
    for instr in stages['tac']:
        print(str(instr))
    print(f"\n  Total instructions: {len(stages['tac'])}")


def print_optimized(stages):
    """Display optimized TAC with optimization report."""
    print_header("STAGE 5: OPTIMIZATION")
    print("\n  Optimization Report:")
    for line in stages['optimization_report']:
        print(f"    • {line}")
    print(f"\n  Optimized TAC:")
    for instr in stages['optimized_tac']:
        print(str(instr))
    print(f"\n  Instructions: {len(stages['tac'])} → {len(stages['optimized_tac'])}")


def print_bytecode(stages):
    """Display generated bytecode."""
    print_header("STAGE 6: CODE GENERATION (Bytecode)")
    print(f"\n  Function entry points: {stages['functions']}")
    print()
    for i, instr in enumerate(stages['bytecode']):
        print(f"  [{i:04d}] {instr}")
    print(f"\n  Total bytecode instructions: {len(stages['bytecode'])}")


def main():
    if len(sys.argv) < 2:
        print("MiniLang Compiler v1.0")
        print("Usage: python main.py <command> <file.mini>")
        print()
        print("Commands:")
        print("  run       Compile and run the program")
        print("  tokens    Show lexer output (token stream)")
        print("  ast       Show Abstract Syntax Tree")
        print("  semantic  Show symbol table from semantic analysis")
        print("  ir        Show Three-Address Code (before optimization)")
        print("  optimize  Show optimized TAC with report")
        print("  bytecode  Show generated bytecode")
        print("  trace     Run with VM execution trace")
        print("  all       Show ALL compiler stages")
        sys.exit(1)

    command = sys.argv[1].lower()

    if len(sys.argv) < 3:
        print("Error: Please specify a source file")
        print("Usage: python main.py <command> <file.mini>")
        sys.exit(1)

    filepath = sys.argv[2]
    if not os.path.exists(filepath):
        print(f"Error: File not found: {filepath}")
        sys.exit(1)

    with open(filepath, 'r') as f:
        source = f.read()

    print(f"\n  Source file: {filepath}")
    print(f"  Source size: {len(source)} characters")

    compiler = Compiler()

    try:
        if command == 'run':
            output = compiler.compile_and_run(source)
            print_header("PROGRAM OUTPUT")
            for line in output:
                print(f"  {line}")

        elif command == 'tokens':
            stages = compiler.compile_step_by_step(source)
            print_tokens(stages)

        elif command == 'ast':
            stages = compiler.compile_step_by_step(source)
            print_ast(stages)

        elif command == 'semantic':
            stages = compiler.compile_step_by_step(source)
            print_symbol_table(stages)

        elif command == 'ir':
            stages = compiler.compile_step_by_step(source)
            print_tac(stages)

        elif command == 'optimize':
            stages = compiler.compile_step_by_step(source)
            print_optimized(stages)

        elif command == 'bytecode':
            stages = compiler.compile_step_by_step(source)
            print_bytecode(stages)

        elif command == 'trace':
            from src.vm import VM
            stages = compiler.compile_step_by_step(source)
            vm = VM(stages['bytecode'], stages['functions'], trace=True)
            output = vm.run()
            print_header("STAGE 7: VM EXECUTION TRACE")
            for entry in vm.trace_log[-50:]:  # Last 50 entries
                print(f"  {entry}")
            if len(vm.trace_log) > 50:
                print(f"\n  ... ({len(vm.trace_log) - 50} earlier entries omitted)")
            print_header("PROGRAM OUTPUT")
            for line in output:
                print(f"  {line}")
            print(f"\n  Total steps: {vm.step_count}")

        elif command == 'all':
            stages = compiler.compile_step_by_step(source)
            print_tokens(stages)
            print_ast(stages)
            print_symbol_table(stages)
            print_tac(stages)
            print_optimized(stages)
            print_bytecode(stages)

            # Now run it
            from src.vm import VM
            vm = VM(stages['bytecode'], stages['functions'], trace=True)
            output = vm.run()
            print_header("STAGE 7: VM EXECUTION (Runtime Environment)")
            for entry in vm.trace_log[-30:]:
                print(f"  {entry}")
            if len(vm.trace_log) > 30:
                print(f"\n  ... ({len(vm.trace_log) - 30} earlier entries omitted)")
            print_header("PROGRAM OUTPUT")
            for line in output:
                print(f"  {line}")
            print(f"\n  Total execution steps: {vm.step_count}")

        else:
            print(f"Unknown command: {command}")
            print("Valid commands: run, tokens, ast, semantic, ir, optimize, bytecode, trace, all")
            sys.exit(1)

    except CompilerError as e:
        print(f"\n  ❌ COMPILATION ERROR: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
