"""
MiniLang Compiler — Orchestrator
==================================
Chains all compiler stages together into a unified pipeline.

Provides both compile_and_run() for direct execution and
compile_step_by_step() that returns all intermediate representations
(used by the web visualizer for presentation).
"""

import json
from typing import Dict, Any, List, Optional

from .lexer import Lexer
from .parser import Parser
from .semantic import SemanticAnalyzer
from .ir_generator import IRGenerator
from .optimizer import Optimizer
from .codegen import CodeGenerator, OpCode
from .vm import VM
from .errors import CompilerError


class Compiler:
    """
    MiniLang Compiler — chains all 7 stages together.

    Usage:
        compiler = Compiler()
        output = compiler.compile_and_run(source_code)
        # or
        stages = compiler.compile_step_by_step(source_code)
    """

    def compile_and_run(self, source: str, trace: bool = False,
                        inputs: List[str] = None) -> List[str]:
        """
        Compile and execute source code in one shot.
        Returns the program output as a list of strings.
        """
        stages = self.compile_step_by_step(source)

        # Run on the VM
        vm = VM(stages['bytecode'], stages['functions'], trace=trace)
        output = vm.run(inputs)

        if trace:
            stages['trace'] = vm.trace_log

        return output

    def compile_step_by_step(self, source: str) -> Dict[str, Any]:
        """
        Compile source code and return all intermediate representations.
        
        Returns a dictionary with:
          - tokens: List of tokens from lexer
          - ast: Abstract Syntax Tree
          - symbol_table: Symbol table from semantic analysis
          - tac: Three-Address Code (before optimization)
          - optimized_tac: Three-Address Code (after optimization)
          - optimization_report: What the optimizer did
          - bytecode: Generated bytecode
          - functions: Function address table
        """
        result = {}

        # Stage 1: Lexical Analysis
        lexer = Lexer(source)
        tokens = lexer.tokenize()
        result['tokens'] = tokens

        # Stage 2: Parsing
        parser = Parser(tokens)
        ast = parser.parse()
        result['ast'] = ast

        # Extract parsing metadata for visualizer
        if hasattr(ast, 'parsing_metadata'):
            result['parsing_metadata'] = ast.parsing_metadata
        # Stage 3: Semantic Analysis
        analyzer = SemanticAnalyzer()
        analyzer.analyze(ast)
        result['symbol_table'] = analyzer.symbol_table
        result['annotated_ast'] = ast  # AST now has resolved_type on nodes

        # Stage 4: IR Generation (Three-Address Code)
        ir_gen = IRGenerator()
        tac = ir_gen.generate(ast)
        result['tac'] = tac

        # Stage 5: Optimization
        optimizer = Optimizer()
        optimized_tac, opt_report = optimizer.optimize(tac)
        result['optimized_tac'] = optimized_tac
        result['optimization_report'] = opt_report

        # Stage 6: Code Generation (Bytecode)
        codegen = CodeGenerator()
        bytecode = codegen.generate(optimized_tac)
        result['bytecode'] = bytecode
        result['functions'] = codegen.functions

        return result

    @staticmethod
    def stages_to_json(stages: Dict[str, Any]) -> Dict[str, Any]:
        """Convert all stage results to JSON-serializable format (for the visualizer)."""
        result = {}

        # Tokens
        result['tokens'] = [
            {
                'type': t.type.name,
                'value': repr(t.value) if isinstance(t.value, str) else str(t.value),
                'line': t.line,
                'column': t.column,
            }
            for t in stages['tokens']
        ]

        # AST
        result['ast'] = stages['ast'].pretty_print()
        if 'parsing_metadata' in stages:
            result['parsing_metadata'] = stages['parsing_metadata']

        # Symbol Table
        result['symbol_table'] = stages['symbol_table'].pretty_print()

        # TAC (before optimization)
        result['tac'] = [str(instr) for instr in stages['tac']]

        # Optimized TAC
        result['optimized_tac'] = [str(instr) for instr in stages['optimized_tac']]

        # Optimization report
        result['optimization_report'] = stages['optimization_report']

        # Bytecode
        result['bytecode'] = [
            {'index': i, 'instruction': str(instr)}
            for i, instr in enumerate(stages['bytecode'])
        ]

        # Functions
        result['functions'] = stages['functions']

        return result
